event_list:
    path:     /
    defaults: { _controller: AppBundle:Event:eventList }
event_list_my:
    path:   /myevents
    defaults: {_controller: AppBundle:Event:eventListMy}
event_participate:
    path:   /participate
    defaults: {_controller: AppBundle:Event:eventListParticipate}
event_list_my_invitations:
    path:   /invitations
    defaults: {_controller: AppBundle:Event:eventListMyInvitations}
events_upcomming:
    path:     /eventsUpcomming
    defaults: { _controller: AppBundle:Event:eventsUpcomming }

event_details:
    path:     /eventDetails/{id}
    defaults: { _controller: AppBundle:Event:eventDetails }

event_new:
    path:     /newEvent
    defaults: { _controller: AppBundle:Event:newEvent }

join_event:
    path:     /joinEvent/{id}
    defaults: { _controller: AppBundle:Event:joinEvent }

event_near:
    path:   /near
    defaults: {_controller: AppBundle:Event:near}
remove_user:
    path:   /remove/user/{id}/{userId}
    defaults: {_controller: AppBundle:Event:removeUser}
    
    
    
invitation_invite:
    path:     /invite/{id}/{eventId}
    defaults: { _controller: AppBundle:Invitation:invite }

invitation_accept:
    path:     /accept/{invitationId}
    defaults: { _controller: AppBundle:Invitation:accept }

invitation_cancel:
    path:     /cancel/{invitationId}
    defaults: { _controller: AppBundle:Invitation:cancel }

invitation_reject:
    path:     /reject/{invitationId}
    defaults: { _controller: AppBundle:Invitation:reject }
